export const empty_monster = {
    name: "Monster",
    size: "medium",
    type: "humanoid",
    tag: "",
    alignment: "any alignment",
    hitDice: 5,
    armorName: "none",
    shieldBonus: 0,
    natArmorBonus: 3,
    otherArmorDesc: "10 (armor)",
    speed: 30,
    burrowSpeed: 0,
    climbSpeed: 0,
    flySpeed: 0,
    hover: false,
    swimSpeed: 0,
    customHP: false,
    customSpeed: false,
    hpText: "4 (1d8)",
    speedDesc: "30 ft.",
    strPoints: 10,
    dexPoints: 10,
    conPoints: 10,
    intPoints: 10,
    wisPoints: 10,
    chaPoints: 10,
    blindsight: 0,
    blind: false,
    darkvision: 0,
    tremorsense: 0,
    truesight: 0,
    telepathy: 0,
    cr: 1,
    customCr: "",
    customProf: 2,
    isLegendary: false,
    legendariesDescription: "",
    isLair: false,
    lairDescription: "",
    lairDescriptionEnd: "",
    isMythic: false,
    mythicDescription: "",
    isRegional: false,
    regionalDescription: "",
    regionalDescriptionEnd: "",
    properties: [],
    abilities: [],
    actions: [],
    bonusActions: [],
    reactions: [],
    legendaries: [],
    mythics: [],
    lairs: [],
    regionals: [],
    sthrows: [],
    skills: [],
    damagetypes: [],
    specialdamage: [],
    conditions: [],
    languages: [],
    understandsBut: "",
    shortName: "",
    pluralName: "",
    doubleColumns: false,
    separationPoint: 1
};