export const open5eApi = "https://api.open5e.com/";

export const defaultStatblock = {
  name: "Monster",
  size: "medium",
  type: "humanoid",
  otherType: "",
  tag: "",
  alignment: "any alignment",
  hitDice: 5,
  hpText: "4 (1d8)",
  customHP: false,
  armorName: "none",
  shieldBonus: 0,
  natArmorBonus: 3,
  otherArmorDesc: "10 (armor)",
  speed: 30,
  burrowSpeed: 0,
  climbSpeed: 0,
  flySpeed: 0,
  hover: false,
  swimSpeed: 0,
  customSpeed: false,
  speedDesc: "30 ft.",
  strPoints: 10,
  dexPoints: 10,
  conPoints: 10,
  intPoints: 10,
  wisPoints: 10,
  chaPoints: 10,
  blindsight: 0,
  blind: false,
  darkvision: 0,
  tremorsense: 0,
  truesight: 0,
  telepathy: 0,
  cr: 1,
  customCr: "",
  customProf: 2,
  isLegendary: false,
  legendariesDescription: "",
  isLair: false,
  lairDescription: "",
  lairDescriptionEnd: "",
  isMythic: false,
  mythicDescription: "",
  isRegional: false,
  regionalDescription: "",
  regionalDescriptionEnd: "",
  properties: [],
  abilities: [],
  actions: [],
  bonusActions: [],
  reactions: [],
  legendaries: [],
  mythics: [],
  lairs: [],
  regionals: [],
  sthrows: [],
  skills: [],
  damagetypes: [],
  specialdamage: [],
  conditions: [],
  languages: [],
  understandsBut: "",
  shortName: "",
  pluralName: "",
  doubleColumns: false,
  separationPoint: 1,
};

export const sizes = [
  { value: "tiny", name: "Tiny" },
  { value: "small", name: "Small" },
  { value: "medium", name: "Medium" },
  { value: "large", name: "Large" },
  { value: "huge", name: "Huge" },
  { value: "gargantuan", name: "Gargantuan" },
];

export const types = [
  { value: "aberration", name: "Aberration" },
  { value: "beast", name: "Beast" },
  { value: "celestial", name: "Celestial" },
  { value: "construct", name: "Construct" },
  { value: "dragon", name: "Dragon" },
  { value: "elemental", name: "Elemental" },
  { value: "fey", name: "Fey" },
  { value: "fiend", name: "Fiend" },
  { value: "giant", name: "Giant" },
  { value: "humanoid", name: "Humanoid" },
  { value: "monstrosity", name: "Monstrosity" },
  { value: "ooze", name: "Ooze" },
  { value: "plant", name: "Plant" },
  { value: "undead", name: "Undead" },
  { value: "*", name: "Other" },
];
